apiVersion: apps/v1
kind: Deployment
metadata:
  name: da-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: da-api
  template:
    metadata:
      labels:
        app: da-api
    spec:
      # imagePullSecrets tells Kubernetes to use the created secret (kubectl create secret docker-registry ghcr-secret ...) whenever it needs to pull images for Pods in this Deployment.
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: da-api
          image: ghcr.io/jeremiah-osidele-projects/da-api:468d5260da6c3026e4d4ac58bad575cbe8d8c7a7
          imagePullPolicy: Always # forces Kubernetes to try to pull each time (safer for production when using :latest
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "da_api"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: password
          ports:
            - containerPort: 8080
