apiVersion: v1
kind: Service
metadata:
  name: da-api
spec:
  type: NodePort
  selector:
    app: da-api
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080


# type: NodePort exposes the service on each nodeâ€™s IP at nodePort.
# In minikube, the node IP is returned by minikube ip.